<div class="clear"></div>
</div><!-- end id centercol, centerwide, or centeronly -->
<!-- ################################################ FOOTER ################################################ -->
<div id="footwrap">
<div id="footer">
<div id="govlogo"><a href="https://www.nasa.gov/"><img src="/webdings/FirstGov_Logo.gif" width="195" height="59" alt="FirstGov logo as link to firstGov site" /></a></div><!-- close id govlogo -->
<div id="govlogotext"><a href="https://umd.service-now.com/itsc?id=kb_article&article=KB0012192" onclick="this.target='_blank'" class="external">Privacy</a> / Copyright
<br /><a href="https://www.hq.nasa.gov/pao/FOIA/" onclick="this.target='_blank'" class="external">Freedom of Information Act</a></div><!-- close id govlogotext -->
<div class="placeholder">&nbsp;</div>
<div id="mdlogo"><img src="/webdings/UM_primarysm.gif" width="185" height="32" alt="UMD Logo ball" />
</div><!-- close id mdlogo -->
<div id="whotext">SBN Webmaster: <!-- <a href="/mailto.shtml" onmouseover="this.href='mai' + 'lto:' + 'warnerem' + '@' + 'astro.umd.edu'">Elizabeth Warner</a> -->
<script type="text/javascript" language="JavaScript">
document.write('<a h'+'ref="m'+'ailt'+'o:'+'%77%61%72%6e%65%72%65%6d%40%61%73%74%72%6f%2e%75%6d%64%2e%65%64%75">&#69;&#108;&#105;&#122;&#97;&#98;&#101;&#116;&#104;&#32;&#87;&#97;&#114;&#110;&#101;&#114;<\/a>');
</script>
<br />SBN Mgr: <!-- <a href="/mailto.shtml" onmouseover="this.href='mai' + 'lto:' + 'ludmilla' + '@' + 'astro.umd.edu'">Dr. Ludmilla Kolokolova</a> -->
<script type="text/javascript" language="JavaScript">
document.write('<a hre'+'f="ma'+'ilto'+':'+'%6c%75%64%6d%69%6c%6c%61%40%61%73%74%72%6f%2e%75%6d%64%2e%65%64%75">&#68;&#114;&#46;&#32;&#76;&#117;&#100;&#109;&#105;&#108;&#108;&#97;&#32;&#75;&#111;&#108;&#111;&#107;&#111;&#108;&#111;&#118;&#97;<\/a>');
</script>
<br><br><em><strong><a href="https://umd.edu/web-accessibility" onclick="this.target='_blank'">Web Accessibility</a></strong></em>
<br>
