<p>2020-01-09 21:40:13 (GMT)</p>
<h2>MariaDB mpc_development:</h2>
<table>
<tr>
<th>Table</th>
<th>Count</th>
<th>Created_at</th>
<th>Updated_at</th>
</tr>
<tr>
<td>close_approaches </td>
<td style="text-align: right;">223366 </td>
<td>2019-05-23 19:22:13 </td>
<td style="color:red;">2019-05-23 19:22:13 </td>
</tr>
<tr>
<td>comet_names </td>
<td style="text-align: right;">4586 </td>
<td>2017-03-15 16:46:33 </td>
<td style="color:red;">2017-03-15 16:46:33 </td>
</tr>
<tr>
<td>comet_orbit_uncertainties </td>
<td style="text-align: right;">1015 </td>
<td>2019-06-04 12:15:27 </td>
<td style="color:red;">2019-06-04 12:15:27 </td>
</tr>
<tr>
<td>comet_orbits </td>
<td style="text-align: right;">9932 </td>
<td>2020-01-09 19:51:25 </td>
<td style="color:blue;">2020-01-09 20:31:03 </td>
</tr>
<tr>
<td>identifications </td>
<td style="text-align: right;">531110 </td>
<td>2020-01-09 12:00:40 </td>
<td style="color:blue;">2020-01-09 12:00:40 </td>
</tr>
<tr>
<td>isolated_tracklets </td>
<td style="text-align: right;">26494461 </td>
<td>2014-12-21 00:01:48 </td>
<td style="color:blue;">2020-01-09 20:52:32 </td>
</tr>
<tr>
<td>mpc_indices </td>
<td style="text-align: right;">395 </td>
<td>2020-01-09 21:30:02 </td>
<td style="color:blue;">2020-01-09 21:30:02 </td>
</tr>
<tr>
<td>numbered_identifications </td>
<td style="text-align: right;">892217 </td>
<td>2019-12-13 03:57:42 </td>
<td style="color:red;">2019-12-13 03:57:42 </td>
</tr>
<tr>
<td>numbered_mps </td>
<td style="text-align: right;">542163 </td>
<td>2019-12-13 04:06:48 </td>
<td style="color:red;">2019-12-13 04:06:48 </td>
</tr>
<tr>
<td>obs_request_observers </td>
<td style="text-align: right;">52 </td>
<td>2019-07-24 16:57:48 </td>
<td style="color:red;">2019-07-24 16:57:48 </td>
</tr>
<tr>
<td>obs_request_users </td>
<td style="text-align: right;">7 </td>
<td>2015-12-04 00:25:22 </td>
<td style="color:red;">2015-12-04 00:25:22 </td>
</tr>
<tr>
<td>observations </td>
<td style="text-align: right;">236041294 </td>
<td>2020-01-09 19:51:21 </td>
<td style="color:blue;">2020-01-09 19:51:21 </td>
</tr>
<tr>
<td>orbit_uncertainties </td>
<td style="text-align: right;">787382 </td>
<td>2019-06-04 12:15:23 </td>
<td style="color:red;">2019-12-13 04:05:26 </td>
</tr>
<tr>
<td>orbits </td>
<td style="text-align: right;">932786 </td>
<td>2020-01-09 16:59:12 </td>
<td style="color:blue;">2020-01-09 17:31:03 </td>
</tr>
<tr>
<td>perturbed_orbits </td>
<td style="text-align: right;">175741560 </td>
<td>2018-09-27 13:20:33 </td>
<td style="color:red;">2018-09-27 13:20:33 </td>
</tr>
<tr>
<td>radar_observations </td>
<td style="text-align: right;">1507 </td>
<td>2019-05-30 03:12:41 </td>
<td style="color:red;">2019-05-30 03:12:41 </td>
</tr>
</table>
<h2>Postgres mpcbeta:</h2>
<table>
<tr>
<th>Table</th>
<th>Count</th>
<th>Created_at</th>
<th>Updated_at</th>
</tr>
<tr>
<td>neocp_els </td>
<td style="text-align: right;">20 </td>
<td>2020-01-01 02:44:02.851963 </td>
<td style="color:blue;">2020-01-09 16:47:14.730218 </td>
</tr>
<tr>
<td>neocp_events </td>
<td style="text-align: right;">31539 </td>
<td>2020-01-09 19:53:11.409968 </td>
<td style="color:blue;">2020-01-09 19:53:11.409968 </td>
</tr>
<tr>
<td>neocp_obs_archive </td>
<td style="text-align: right;">97120 </td>
<td>2020-01-09 12:27:44.007447 </td>
<td style="color:blue;">2020-01-09 12:27:44.007447 </td>
</tr>
<tr>
<td>neocp_obs </td>
<td style="text-align: right;">660 </td>
<td>2020-01-09 12:27:44.001898 </td>
<td style="color:blue;">2020-01-09 12:27:44.001898 </td>
</tr>
<tr>
<td>neocp_prev_des </td>
<td style="text-align: right;">33214 </td>
<td>2020-01-09 19:53:11.145583 </td>
<td style="color:blue;">2020-01-09 19:53:11.145583 </td>
</tr>
<tr>
<td>neocp_var </td>
<td style="text-align: right;">40320 </td>
<td>2020-01-09 16:47:22.521433 </td>
<td style="color:blue;">2020-01-09 16:47:22.521433 </td>
</tr>
</table>
<br>
<p style="color:red;">YYYY-MM-DD - latest record is older than 3 days</p>
<p style="color:orange;">YYYY-MM-DD - latest record is older than 1 day</p>
<p style="color:blue;">YYYY-MM-DD - latest record is less than 1 day old</p>
